name: 'Test PR Action'
description: 'Automatically test pull requests and optionally auto-merge Dependabot PRs when tests pass'
author: 'phucbm'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  dependabot-auto-merge:
    description: 'Auto-merge Dependabot PRs if tests pass (true/false)'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for commenting and merging'
    required: false
    default: ${{ github.token }}
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '18'
  package-manager:
    description: 'Package manager to use (npm, pnpm, yarn)'
    required: false
    default: 'auto'

runs:
  using: 'composite'
  steps:
    - name: Check if triggered by comment
      id: comment-check
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
          # Check if comment contains test commands
          comment="${{ github.event.comment.body }}"
          if [[ "$comment" =~ ^/test($|[[:space:]]) ]] || [[ "$comment" =~ ^/retest($|[[:space:]]) ]]; then
            echo "triggered=true" >> $GITHUB_OUTPUT
            echo "auto_merge=false" >> $GITHUB_OUTPUT
          elif [[ "$comment" =~ ^/test-merge($|[[:space:]]) ]]; then
            echo "triggered=true" >> $GITHUB_OUTPUT
            echo "auto_merge=true" >> $GITHUB_OUTPUT
          else
            echo "triggered=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "triggered=true" >> $GITHUB_OUTPUT
          echo "auto_merge=${{ inputs.dependabot-auto-merge }}" >> $GITHUB_OUTPUT
        fi

    - name: Exit if not triggered
      if: steps.comment-check.outputs.triggered == 'false'
      shell: bash
      run: exit 0

    - name: Checkout code
      if: steps.comment-check.outputs.triggered == 'true'
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github-token }}
        ref: ${{ github.event.pull_request.head.sha || github.event.pull_request.head.ref }}

    - name: Setup Node.js
      if: steps.comment-check.outputs.triggered == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Detect package manager
      if: steps.comment-check.outputs.triggered == 'true'
      id: detect-pm
      shell: bash
      run: |
        if [[ "${{ inputs.package-manager }}" != "auto" ]]; then
          echo "pm=${{ inputs.package-manager }}" >> $GITHUB_OUTPUT
        elif [[ -f "pnpm-lock.yaml" ]]; then
          echo "pm=pnpm" >> $GITHUB_OUTPUT
        elif [[ -f "yarn.lock" ]]; then
          echo "pm=yarn" >> $GITHUB_OUTPUT
        else
          echo "pm=npm" >> $GITHUB_OUTPUT
        fi

    - name: Setup PNPM
      if: steps.comment-check.outputs.triggered == 'true' && steps.detect-pm.outputs.pm == 'pnpm'
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Check for test script
      if: steps.comment-check.outputs.triggered == 'true'
      id: check-test
      shell: bash
      run: |
        if [[ -f "package.json" ]] && jq -e '.scripts.test' package.json > /dev/null; then
          echo "has_test=true" >> $GITHUB_OUTPUT
          echo "test_script=$(jq -r '.scripts.test' package.json)" >> $GITHUB_OUTPUT
        else
          echo "has_test=false" >> $GITHUB_OUTPUT
        fi

    - name: Install dependencies
      if: steps.comment-check.outputs.triggered == 'true' && steps.check-test.outputs.has_test == 'true'
      shell: bash
      run: |
        case "${{ steps.detect-pm.outputs.pm }}" in
          "pnpm")
            pnpm install --no-frozen-lockfile
            ;;
          "yarn")
            yarn install --no-immutable
            ;;
          *)
            npm ci
            ;;
        esac

    - name: Run tests
      if: steps.comment-check.outputs.triggered == 'true' && steps.check-test.outputs.has_test == 'true'
      id: run-tests
      shell: bash
      run: |
        echo "Running tests..."
        case "${{ steps.detect-pm.outputs.pm }}" in
          "pnpm")
            pnpm test
            ;;
          "yarn")
            yarn test
            ;;
          *)
            npm test
            ;;
        esac
        echo "tests_passed=true" >> $GITHUB_OUTPUT
      continue-on-error: true

    - name: Check test results
      if: steps.comment-check.outputs.triggered == 'true' && steps.check-test.outputs.has_test == 'true'
      id: test-results
      shell: bash
      run: |
        if [[ "${{ steps.run-tests.outcome }}" == "success" ]]; then
          echo "tests_passed=true" >> $GITHUB_OUTPUT
        else
          echo "tests_passed=false" >> $GITHUB_OUTPUT
        fi

    - name: Comment on PR - Tests passed
      if: steps.comment-check.outputs.triggered == 'true' && steps.check-test.outputs.has_test == 'true' && steps.test-results.outputs.tests_passed == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const prNumber = context.payload.pull_request?.number || context.payload.issue?.number;
          const isDependabot = context.actor === 'dependabot[bot]';
          const autoMergeEnabled = '${{ inputs.dependabot-auto-merge }}' === 'true';
          const packageManager = '${{ steps.detect-pm.outputs.pm }}';
          const triggerType = '${{ github.event_name }}' === 'issue_comment' ? 'comment' : 'pull request event';
          
          let body = `✅ **Tests passed!** All tests completed successfully.\n\n`;
          body += `📦 **Package manager:** ${packageManager}\n`;
          body += `_Triggered by: ${triggerType}_`;
          
          // Add instructions
          body += '\n\n---\n<details>\n<summary>Test PR Action commands and options</summary>\n<br />\n\n';
          body += 'You can trigger test actions by commenting on this PR:\n';
          body += '- `/test` will run tests and comment the results\n';
          body += '- `/retest` will re-run tests and comment the results\n';
          
          if (isDependabot) {
            body += '- `/test-merge` will run tests and auto-merge this Dependabot PR if tests pass\n';
            if (!autoMergeEnabled) {
              body += '\n💡 **Tip**: Auto-merge is currently disabled. Use `/test-merge` to merge this PR after testing.\n';
            }
          } else {
            body += '- `/test-merge` will run tests (auto-merge only works for Dependabot PRs)\n';
          }
          
          body += '\n</details>';
          
          // Add branding footer
          body += '\n\n---\n🤖 *Automated by [Test PR Action](https://github.com/phucbm/test-pr-action) by @phucbm*';
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: body
          });

    - name: Comment on PR - Tests failed
      if: steps.comment-check.outputs.triggered == 'true' && steps.check-test.outputs.has_test == 'true' && steps.test-results.outputs.tests_passed == 'false'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const prNumber = context.payload.pull_request?.number || context.payload.issue?.number;
          const packageManager = '${{ steps.detect-pm.outputs.pm }}';
          const triggerType = '${{ github.event_name }}' === 'issue_comment' ? 'comment' : 'pull request event';
          
          let body = `❌ **Tests failed!** Please check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.\n\n`;
          body += `📦 **Package manager:** ${packageManager}\n`;
          body += `_Triggered by: ${triggerType}_`;
          
          // Add instructions
          body += '\n\n---\n<details>\n<summary>Test PR Action commands and options</summary>\n<br />\n\n';
          body += 'You can trigger test actions by commenting on this PR:\n';
          body += '- `/test` will run tests and comment the results\n';
          body += '- `/retest` will re-run tests and comment the results\n';
          body += '- `/test-merge` will run tests and auto-merge if tests pass (Dependabot PRs only)\n';
          body += '\n💡 **Tip**: Fix the failing tests and use `/retest` to verify the fixes.\n';
          body += '\n</details>';
          
          // Add branding footer
          body += '\n\n---\n🤖 *Automated by [Test PR Action](https://github.com/phucbm/test-pr-action) by @phucbm*';
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: body
          });

    - name: Comment on PR - No tests
      if: steps.comment-check.outputs.triggered == 'true' && steps.check-test.outputs.has_test == 'false'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const prNumber = context.payload.pull_request?.number || context.payload.issue?.number;
          const isDependabot = context.actor === 'dependabot[bot]';
          const autoMergeEnabled = '${{ inputs.dependabot-auto-merge }}' === 'true';
          const packageManager = '${{ steps.detect-pm.outputs.pm }}';
          const triggerType = '${{ github.event_name }}' === 'issue_comment' ? 'comment' : 'pull request event';
          
          let body = `ℹ️ **No test script found** in package.json. Skipping tests.\n\n`;
          body += `📦 **Package manager:** ${packageManager}\n`;
          body += `_Triggered by: ${triggerType}_`;
          
          // Add instructions
          body += '\n\n---\n<details>\n<summary>Test PR Action commands and options</summary>\n<br />\n\n';
          body += 'You can trigger test actions by commenting on this PR:\n';
          body += '- `/test` will check for tests and comment the results\n';
          body += '- `/retest` will re-check for tests and comment the results\n';
          
          if (isDependabot) {
            body += '- `/test-merge` will auto-merge this Dependabot PR (no tests to run)\n';
            if (autoMergeEnabled) {
              body += '\n💡 **Note**: Auto-merge is enabled for Dependabot PRs when no tests are present.\n';
            }
          } else {
            body += '- `/test-merge` will check for tests (auto-merge only works for Dependabot PRs)\n';
          }
          
          body += '\n💡 **Tip**: Add a `test` script to your package.json to enable automatic testing.\n';
          body += '\n</details>';
          
          // Add branding footer
          body += '\n\n---\n🤖 *Automated by [Test PR Action](https://github.com/phucbm/test-pr-action) by @phucbm*';
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: body
          });

    - name: Auto-merge Dependabot PR
      if: |
        steps.comment-check.outputs.triggered == 'true' && 
        github.actor == 'dependabot[bot]' && 
        (steps.check-test.outputs.has_test == 'false' || steps.test-results.outputs.tests_passed == 'true') &&
        (steps.comment-check.outputs.auto_merge == 'true' || (github.event_name == 'pull_request' && inputs.dependabot-auto-merge == 'true'))
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const prNumber = context.payload.pull_request?.number || context.payload.issue?.number;
          
          // Add auto-merge comment
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: '🤖 **Auto-merging Dependabot PR** - Tests passed and auto-merge is enabled.'
          });
          
          // Enable auto-merge
          await github.rest.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber,
            merge_method: 'squash'
          });